name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:3.24.0 # Atau versi yang Anda gunakan

    steps:
      - uses: actions/checkout@v4

      # Verifikasi channel dan upgrade Flutter
      - run: flutter channel stable
      - run: flutter upgrade

      # Verifikasi instalasi Flutter
      - run: flutter doctor

      # Build aplikasi Flutter Web
      - run: flutter build web

      # Deploy ke Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTOCV27 }}
          channelId: live
          projectId: portocv27
